services:
  db:
    image: postgres:15
    container_name: postgres_fastapi
    restart: always
    environment:
      POSTGRES_USER: meuusuario
      POSTGRES_PASSWORD: minhasenha
      POSTGRES_DB: meubanco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer_fastapi
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data: