"""adicionando tabela referencia no endereco

Revision ID: 1886ea0a1c82
Revises: d9fa65f802ba
Create Date: 2025-07-10 23:06:15.855894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1886ea0a1c82'
down_revision: Union[str, None] = 'd9fa65f802ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endereco', sa.Column('referencia', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endereco', 'referencia')
    # ### end Alembic commands ###
