"""alterando modelo de listagem2

Revision ID: 25272fe463c3
Revises: 495e517a5a18
Create Date: 2025-06-19 03:44:39.511974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25272fe463c3'
down_revision: Union[str, None] = '495e517a5a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listagem', sa.Column('descricao', sa.String(length=255), nullable=True))
    op.drop_column('produto', 'descricao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('descricao', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('listagem', 'descricao')
    # ### end Alembic commands ###
