"""adicionando tabela titulo no endereco

Revision ID: 3cd8dbc42335
Revises: 1886ea0a1c82
Create Date: 2025-07-10 23:11:14.437766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cd8dbc42335'
down_revision: Union[str, None] = '1886ea0a1c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endereco', sa.Column('titulo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endereco', 'titulo')
    # ### end Alembic commands ###
