"""adicionando nome_impresso e nome_cartao

Revision ID: 410687ce030b
Revises: 3cd8dbc42335
Create Date: 2025-07-12 20:03:50.983281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '410687ce030b'
down_revision: Union[str, None] = '3cd8dbc42335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forma_pagamento', sa.Column('nome_impresso', sa.String(), nullable=True))
    op.add_column('forma_pagamento', sa.Column('nome_cartao', sa.String(), nullable=True))
    op.drop_column('forma_pagamento', 'nome_no_cartao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forma_pagamento', sa.Column('nome_no_cartao', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('forma_pagamento', 'nome_cartao')
    op.drop_column('forma_pagamento', 'nome_impresso')
    # ### end Alembic commands ###
