"""tirando model de forma pagamento e criando pagamento novamente

Revision ID: 41e442ae04fe
Revises: 9c3fc1255f3e
Create Date: 2025-07-20 21:59:27.411835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41e442ae04fe'
down_revision: Union[str, None] = '9c3fc1255f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
