"""adicionando id de imagens

Revision ID: 43cfedd88662
Revises: 41e442ae04fe
Create Date: 2025-07-24 21:04:01.594349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43cfedd88662'
down_revision: Union[str, None] = '41e442ae04fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_forma_pagamento_id', table_name='forma_pagamento')
    op.drop_table('forma_pagamento')
    op.add_column('listagem', sa.Column('foto_id', sa.String(length=50), nullable=True))
    op.alter_column('listagem', 'foto',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.add_column('produtor', sa.Column('banner_id', sa.String(), nullable=True))
    op.add_column('produtor', sa.Column('foto_id', sa.String(), nullable=True))
    op.add_column('usuario', sa.Column('foto_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'foto_id')
    op.drop_column('produtor', 'foto_id')
    op.drop_column('produtor', 'banner_id')
    op.alter_column('listagem', 'foto',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('listagem', 'foto_id')
    op.create_table('forma_pagamento',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gateway', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('token_gateway', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bandeira', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('final_cartao', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nome_impresso', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nome_cartao', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='forma_pagamento_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='forma_pagamento_pkey')
    )
    op.create_index('ix_forma_pagamento_id', 'forma_pagamento', ['id'], unique=False)
    # ### end Alembic commands ###
