"""colocando tamanho nos varchar

Revision ID: 4e1492a6c05b
Revises: ce4267d474b0
Create Date: 2025-08-04 16:08:09.166194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e1492a6c05b'
down_revision: Union[str, None] = 'ce4267d474b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_pedido', sa.Column('nome_personalizado_comprado', sa.String(length=255), nullable=True))
    op.add_column('item_pedido', sa.Column('valor_unitario_comprado', sa.Integer(), nullable=True))
    op.drop_column('item_pedido', 'nome_personalizado')
    op.drop_column('item_pedido', 'valor_unitario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_pedido', sa.Column('valor_unitario', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('item_pedido', sa.Column('nome_personalizado', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('item_pedido', 'valor_unitario_comprado')
    op.drop_column('item_pedido', 'nome_personalizado_comprado')
    # ### end Alembic commands ###
