"""adicionando listagem.id no itempedido

Revision ID: 6829306105e6
Revises: 70890b7984af
Create Date: 2025-07-19 22:48:12.307657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6829306105e6'
down_revision: Union[str, None] = '70890b7984af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_pedido', sa.Column('listagem_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item_pedido', 'listagem', ['listagem_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_pedido', type_='foreignkey')
    op.drop_column('item_pedido', 'listagem_id')
    # ### end Alembic commands ###
