"""minha alteração

Revision ID: 70890b7984af
Revises: 2d912ec2a2de
Create Date: 2025-07-19 21:54:26.755942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70890b7984af'
down_revision: Union[str, None] = '2d912ec2a2de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('sazonal', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produto_id'), 'produto', ['id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpf_cnpj', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('e_vendedor', sa.Boolean(), nullable=True),
    sa.Column('avaliacao', sa.String(), nullable=True),
    sa.Column('foto_perfil', sa.String(), nullable=True),
    sa.Column('telefone_1', sa.String(), nullable=True),
    sa.Column('telefone_2', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_cpf_cnpj'), 'usuario', ['cpf_cnpj'], unique=True)
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('rua', sa.String(), nullable=True),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('referencia', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endereco_id'), 'endereco', ['id'], unique=False)
    op.create_table('forma_pagamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('gateway', sa.String(), nullable=False),
    sa.Column('token_gateway', sa.String(), nullable=False),
    sa.Column('bandeira', sa.String(), nullable=True),
    sa.Column('final_cartao', sa.String(), nullable=True),
    sa.Column('nome_impresso', sa.String(), nullable=True),
    sa.Column('nome_cartao', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forma_pagamento_id'), 'forma_pagamento', ['id'], unique=False)
    op.create_table('notificacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('banner', sa.String(), nullable=True),
    sa.Column('foto', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('rua', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('usuario_produto_favorito',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'produto_id')
    )
    op.create_table('certificado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produtor_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('instituicao', sa.String(), nullable=True),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.Column('arquivo', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produtor_id'], ['produtor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listagem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('nome_personalizado', sa.String(length=255), nullable=True),
    sa.Column('preco', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('estoque', sa.Integer(), nullable=True),
    sa.Column('produtor_id', sa.Integer(), nullable=False),
    sa.Column('preco_promocional', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('unidade', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('foto', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['produtor_id'], ['produtor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Integer(), nullable=True),
    sa.Column('momento_compra', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('group_hash', sa.String(), nullable=True),
    sa.Column('avaliacao', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('id_endereco', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_endereco'], ['endereco.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_group_hash'), 'pedido', ['group_hash'], unique=False)
    op.create_index(op.f('ix_pedido_id'), 'pedido', ['id'], unique=False)
    op.create_table('usuario_produtor_favorito',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('produtor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produtor_id'], ['produtor.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'produtor_id')
    )
    op.create_table('item_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('nome_personalizado', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('valor_unitario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_pedido_id'), 'item_pedido', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_pedido_id'), table_name='item_pedido')
    op.drop_table('item_pedido')
    op.drop_table('usuario_produtor_favorito')
    op.drop_index(op.f('ix_pedido_id'), table_name='pedido')
    op.drop_index(op.f('ix_pedido_group_hash'), table_name='pedido')
    op.drop_table('pedido')
    op.drop_table('listagem')
    op.drop_table('certificado')
    op.drop_table('usuario_produto_favorito')
    op.drop_table('produtor')
    op.drop_table('notificacao')
    op.drop_index(op.f('ix_forma_pagamento_id'), table_name='forma_pagamento')
    op.drop_table('forma_pagamento')
    op.drop_index(op.f('ix_endereco_id'), table_name='endereco')
    op.drop_table('endereco')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_cpf_cnpj'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_produto_id'), table_name='produto')
    op.drop_table('produto')
    # ### end Alembic commands ###
