"""adicionando endereco completo do produtor

Revision ID: 77f61d698993
Revises: 410687ce030b
Create Date: 2025-07-15 00:03:06.940595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77f61d698993'
down_revision: Union[str, None] = '410687ce030b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtor', sa.Column('rua', sa.String(), nullable=True))
    op.add_column('produtor', sa.Column('numero', sa.String(), nullable=True))
    op.add_column('produtor', sa.Column('complemento', sa.String(), nullable=True))
    op.add_column('produtor', sa.Column('bairro', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtor', 'bairro')
    op.drop_column('produtor', 'complemento')
    op.drop_column('produtor', 'numero')
    op.drop_column('produtor', 'rua')
    # ### end Alembic commands ###
