"""alterando modelo de listagem3

Revision ID: 7e8256e17082
Revises: 25272fe463c3
Create Date: 2025-06-20 21:14:19.172565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e8256e17082'
down_revision: Union[str, None] = '25272fe463c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listagem', sa.Column('nome_personalizado', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listagem', 'nome_personalizado')
    # ### end Alembic commands ###
