"""alterando banco do produtor novamente

Revision ID: 9189b46bd039
Revises: 4c2a6b651085
Create Date: 2025-05-13 02:38:31.629468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9189b46bd039'
down_revision: Union[str, None] = '4c2a6b651085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtores', sa.Column('endereco', sa.String(), nullable=True))
    op.add_column('produtores', sa.Column('nome', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtores', 'nome')
    op.drop_column('produtores', 'endereco')
    # ### end Alembic commands ###
