"""adicionando token de recuperacao

Revision ID: 93ab09b1fca7
Revises: 43cfedd88662
Create Date: 2025-08-04 02:09:31.979549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ab09b1fca7'
down_revision: Union[str, None] = '43cfedd88662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('token_recuperacao', sa.String(), nullable=True))
    op.add_column('usuario', sa.Column('token_expira_em', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'token_expira_em')
    op.drop_column('usuario', 'token_recuperacao')
    # ### end Alembic commands ###
