"""adicionadno agrupador de pedido no banco

Revision ID: b88e7f9b1d85
Revises: 2d820a713282
Create Date: 2025-07-16 04:57:44.494373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b88e7f9b1d85'
down_revision: Union[str, None] = '2d820a713282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('group_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_pedido_group_hash'), 'pedido', ['group_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_group_hash'), table_name='pedido')
    op.drop_column('pedido', 'group_hash')
    # ### end Alembic commands ###
