"""tirando data de nascimeno

Revision ID: ce4267d474b0
Revises: 93ab09b1fca7
Create Date: 2025-08-04 02:13:33.081905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce4267d474b0'
down_revision: Union[str, None] = '93ab09b1fca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'data_nascimento')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('data_nascimento', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
