"""criando nova tabela de item_pedido no banco

Revision ID: df8a2fbae2ce
Revises: b88e7f9b1d85
Create Date: 2025-07-16 05:53:11.191809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df8a2fbae2ce'
down_revision: Union[str, None] = 'b88e7f9b1d85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedido', 'produto')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('produto', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
