"""alterando banco do produtor novamente

Revision ID: e52a4eaf7cf4
Revises: 9189b46bd039
Create Date: 2025-05-13 02:39:57.986141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e52a4eaf7cf4'
down_revision: Union[str, None] = '9189b46bd039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtores', sa.Column('foto', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtores', 'foto')
    # ### end Alembic commands ###
