"""minha alteração

Revision ID: f3e5d40f989c
Revises: 410687ce030b
Create Date: 2025-07-19 05:23:44.062217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3e5d40f989c'
down_revision: Union[str, None] = '410687ce030b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endereco', sa.Column('titulo', sa.String(), nullable=True))
    op.add_column('endereco', sa.Column('referencia', sa.String(), nullable=True))
    op.add_column('listagem', sa.Column('nome_personalizado', sa.String(length=255), nullable=True))
    op.add_column('listagem', sa.Column('preco_promocional', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('listagem', sa.Column('unidade', sa.String(length=50), nullable=True))
    op.add_column('listagem', sa.Column('descricao', sa.String(length=255), nullable=True))
    op.add_column('listagem', sa.Column('foto', sa.String(length=100), nullable=True))
    op.alter_column('listagem', 'preco',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
    op.drop_index('ix_listagem_id', table_name='listagem')
    op.drop_column('produto', 'descricao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('descricao', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_listagem_id', 'listagem', ['id'], unique=False)
    op.alter_column('listagem', 'preco',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('listagem', 'foto')
    op.drop_column('listagem', 'descricao')
    op.drop_column('listagem', 'unidade')
    op.drop_column('listagem', 'preco_promocional')
    op.drop_column('listagem', 'nome_personalizado')
    op.drop_column('endereco', 'referencia')
    op.drop_column('endereco', 'titulo')
    # ### end Alembic commands ###
